### ISSUE TITLE
readme states -width flag, -linewidth is in source

### ISSUE THREAD

**Issue by jnflint** [esimov/triangle#10]
from main.go
lineWidth       = flag.Float64("linewidth", 1, "Wireframe line width")

**Comment by esimov** [comment]
Thanks for reporting. The issue is fixed now.

**Comment by jnflint** [comment]
Sorry to bother, the examples in the readme also need updating.
Thanks for the app, I really like the results.

**Comment by esimov** [comment]
@jnflint yes you are right. I will make some code refactoring and will update shortly.

**Comment by esimov** [comment]
@jnflint the typing errors now are corrected. Also i have extended a little bit the library to support the svg result to be accessed via web browser.
