### ISSUE TITLE
How to generate sample10.png?What parameters?

### ISSUE THREAD

**Issue by wodsoe** [esimov/triangle#13]
How to generate sample10.png?What parameters?
Thank you!

**Comment by esimov** [comment]
Try the following command:

triangle -in samples/input_file.jpg -out ~/Desktop/output.png -wf=2 -pts=5500 -stroke=1 -blur=10 -bg=#ffffff00 -noise=10

I have also made some adjustments on the existing code, so please make sure that the code is up to date.

**Comment by wanghaisheng** [comment]
@esimov what about sample7

**Comment by esimov** [comment]
```bash
$ cat samples/j0YwRCc.jpg | triangle-go > ~/Desktop/ouput.jpg -wf=2 -bg=#ffffff00 -stroke=2
```

**Comment by wanghaisheng** [comment]
can you add corresponding code to Readme for more new guys
