### ISSUE TITLE
doesn't seem to work

### ISSUE THREAD

**Issue by pjebs** [esimov/triangle#21]
```
	file, err := os.Open("face.jpg")
	if err != nil {
		log.Fatalf("Error opening the file: %v", err)
	}
	defer file.Close()

	// File to write to
	nf, err := os.Create("trig.jpeg")
	if err != nil {
		log.Fatalf("Error writing the file: %s", err)
	}

	// Run Triangle algorithm
	p := &triangle.Processor{
		// Initialize struct variables
	}
	img := &triangle.Image{*p}
	_, _,_, err = img.Draw(file, nf, func() {})
	if err != nil {
		log.Fatalf("Error creating triangles: %s", err)
	}
```

I keep getting error: `Error creating triangles: image: unknown format`

**Comment by esimov** [comment]
First I would like to ask to download the latest release of the library. Secondly could you send me the image you have tried. My assumption is that your sample image format is unsupported.

**Comment by pjebs** [comment]
```
module facemask

go 1.18

require (
	github.com/esimov/pigo v1.4.5 // indirect
	github.com/esimov/triangle v1.2.4 // indirect
	github.com/fogleman/gg v1.3.0 // indirect
	github.com/golang/freetype v0.0.0-20170609003504-e2365dfdc4a0 // indirect
	golang.org/x/image v0.0.0-20200927104501-e162460cd6b5 // indirect
)

```
![face](https://user-images.githubusercontent.com/5377970/160819208-ffe5b319-3efe-4b33-a0ba-b44178d5cc7d.jpg)

**Comment by esimov** [comment]
This is what I got with MaxPoints: 500.

![trig](https://user-images.githubusercontent.com/883386/160825023-4f914b12-34ae-4a40-9ba3-37ac0336ae11.jpeg)

with the code you just provided, without the initialized parameters the output is this:

![trig](https://user-images.githubusercontent.com/883386/160825154-b19035c5-fd6a-426a-b241-2f1b20e87951.jpeg)

**Comment by pjebs** [comment]
Can you send me your entire file?

**Comment by pjebs** [comment]
This is my full file:


```
package main

import (
	"image"
	"fmt"
	_ "image/jpeg"
	_ "image/png"
	"io/ioutil"
	"log"
	"os"

	"github.com/esimov/pigo/core"
	"github.com/esimov/triangle"
)

func main() {

	cascadeFile, err := ioutil.ReadFile("cascade/facefinder")
	if err != nil {
		log.Fatalf("Error reading the cascade file: %v", err)
	}

	file, err := os.Open("face.jpg")
	if err != nil {
		log.Fatalf("Error opening the file: %v", err)
	}
	defer file.Close()

	src, err := pigo.DecodeImage(file)
	if err != nil {
		log.Fatalf("Cannot open the image file: %v", err)
	}

	pixels := pigo.RgbToGrayscale(src)
	cols, rows := src.Bounds().Max.X, src.Bounds().Max.Y

	cParams := pigo.CascadeParams{
		MinSize:     20,
		MaxSize:     1000,
		ShiftFactor: 0.1,
		ScaleFactor: 1.1,

		ImageParams: pigo.ImageParams{
			Pixels: pixels,
			Rows:   rows,
			Cols:   cols,
			Dim:    cols,
		},
	}

	pigo := pigo.NewPigo()
	// Unpack the binary file. This will return the number of cascade trees,
	// the tree depth, the threshold and the prediction from tree's leaf nodes.
	classifier, err := pigo.Unpack(cascadeFile)
	if err != nil {
		log.Fatalf("Error reading the cascade file: %s", err)
	}

	// Run the classifier over the obtained leaf nodes and return the detection results.
	// The result contains quadruplets representing the row, column, scale and detection score.
	dets := classifier.RunCascade(cParams, 0.0)

	// Calculate the intersection over union (IoU) of two clusters.
	dets = classifier.ClusterDetections(dets, 0.2)

	fd := image.Rectangle{
		Min: image.Point{
			X: int(float64(dets[0].Col) - 0.5*float64(dets[0].Scale)),
			Y: int(float64(dets[0].Row) - 0.5*float64(dets[0].Scale)),
		},
		Max: image.Point{
			X: int(float64(dets[0].Col) + 0.5*float64(dets[0].Scale)),
			Y: int(float64(dets[0].Row) + 0.5*float64(dets[0].Scale)),
		},
	}

	fmt.Println(fd)



	// File write to
	nf, err := os.Create("trig.jpg")
	if err != nil {
		log.Fatalf("Error writing the file: %s", err)
	}

	// Run Triangle algorithm
	p := &triangle.Processor{
		// Initialize struct variables
	}
	img := &triangle.Image{*p}
	_, _,_, err = img.Draw(file, nf, func() {})
	if err != nil {
		log.Fatalf("Error creating triangles: %s", err)
	}

}

```

**Comment by esimov** [comment]
Can you try with a different image?

**Comment by pjebs** [comment]
_, _,_, err = img.Draw(file, nf, func() {})

When I change `file` to `src` it works. No idea why.

**Comment by esimov** [comment]
`DecodeImage` from the Pigo library in the background is doing the same thing as `ToNRGBA` from `Triangle` so it shouldn't make to much difference. In the end both functions are transforming the generic image type to its specific type. I cannot think about anything else why this error is happening is that the file structure of the image you sent to me is not decodable. Is this image downloaded from the internet somehow? If yes, could you point me the address from where it has been downloaded or eventually send as an attachment. I'm asking because I'm afraid once it's uploaded to Github its getting re-encoded.

**Comment by pjebs** [comment]
https://generated.photos/face/joyful-asian-adult-male-with-short-black-hair-and-brown-eyes--5e6846f36d3b380006e3253b

**Comment by pjebs** [comment]
The file can be found here: https://github.com/rocketlaunchr/facemask: `face.jpg`.

The objective of the project is that the face is blurred using your triangle package. But everything else is EXACTLY the same.
If you can tell me why the end result is slightly blurred still, it would be greatly appreciated. The mask is definitely generated correctly: https://github.com/rocketlaunchr/facemask/blob/master/core/facemask.go#L143

**Comment by pjebs** [comment]
Interestingly the `go.mod` file may need to be adjusted to `go 1.18` for it to work (for an unknown reason)

**Comment by esimov** [comment]
I assume you are referring to the face zones outside of the protected face mask, like the person hair. I don't know the reason why it's this way, but I can investigate it.

**Comment by esimov** [comment]
I've debugged a little deeper into the problem and I found the reason why the image is getting blurred out. I will come with a solution shortly.

**Comment by esimov** [comment]
The issue should be fixed now. The problem was that I've enforced the blur radius to be 1 in case is less then 1, otherwise the stackblur algorithm would have panicked. Do not forget to update to the latest (1.2.5) release.

**Comment by pjebs** [comment]
Thanks for looking into it.
