### ISSUE TITLE
Overlapping/excessive triangles

### ISSUE THREAD

**Issue by evilfunnybird** [esimov/triangle#23]
So, whenever I try to triangulate an image, there is a problem with some random triangles that are drawn above the necessary ones. Sometimes they are a something like a line, and sometimes they are gigantic. I tried to change value of all of the parameters/flags but no luck.
In the attached files is the source and generated images with flags: -pts 5000 -blur 1.

![173](https://user-images.githubusercontent.com/40058026/161369387-baffc7b1-d0c6-4f44-b040-6e5317e65ce8.png)
![173](https://user-images.githubusercontent.com/40058026/161369393-fe76dd9f-2363-4119-9e5b-2505ec46338d.svg)
![img31](https://user-images.githubusercontent.com/40058026/161369402-e77641ca-8716-4906-b4b4-095839d52580.png)
![img31](https://user-images.githubusercontent.com/40058026/161369406-c1389bce-94aa-4c9a-820b-6abf6cada1d9.svg)

**Comment by esimov** [comment]
I might try to resolve it but it can be a tricky one.

**Comment by evilfunnybird** [comment]
The thing is, wierd triangles are actually overlapping (there are "normal" triangles underneath) and they are not in the end af the generated file (if they were, I could've just not include them, but figuring out excessive triangles sounds like a resourse-intensive task)

**Comment by esimov** [comment]
I assume you analyzed the svg version.

**Comment by evilfunnybird** [comment]
A little bit, yeah, since I parse it to get triangles for a thing I'm making

**Comment by pjebs** [comment]
![facemask](https://user-images.githubusercontent.com/5377970/161877115-e7c33bb3-b00a-4071-8411-6c4ee06778a3.jpg)

I have the same issue. I don't use any svg features.

**Comment by esimov** [comment]
I was asking because you mentioned that the there are normal triangles underneath the artifacts. Meantime I have checked also myself and that's correct. I don't know yet why, but I will try to debug to understand why this is happening.

**Comment by pjebs** [comment]
![facemask](https://user-images.githubusercontent.com/5377970/161971867-7085d569-933a-4d61-88c1-d86d3a95e0bd.jpg)

Here's an extreme example.

**Comment by pjebs** [comment]
I'm going to assume there was a regression in a recent update to the code. Perhaps in the last year. Because I think you would have seen this effect when you first wrote the package.

**Comment by esimov** [comment]
I restored back to a few commit points to see if these artifacts are still present in the previous versions. Unfortunately this issue is present on the earliest versions too, but they are showing only occasionally.

**Comment by evilfunnybird** [comment]
So, by any chance, do you have an idea, what might cause this issue? For testing purposes I additionally ran this in single and multi thread and with different options, still no luck.

**Comment by esimov** [comment]
I'm sorry for the late response, it was a tricky bug to capture, because it happened only occasionally. The reason was due to wrong type conversion. Because in almost any part of the code base the conversion was from float to int, it happened that in the renamed `polygon.go` file I used integers instead of floats and this affected the end results. During the debugging session I realized that the API does not stand up from the architecture point of view so I have refactored completely the code and also extended with additional features in order to be even more customizable, which results in a more appealing visual output. But this in the next release, which is coming soon.

**Comment by esimov** [comment]
Here is an example of using the old method and the new one.

![triangle_old](https://user-images.githubusercontent.com/883386/163662551-f2fbe0f6-eec0-46f3-a6c9-c40150dee788.png)
![triangle_new](https://user-images.githubusercontent.com/883386/163662580-54252ca9-e7c7-4288-a739-549b71f94689.png)

**Comment by esimov** [comment]
I have published a new [v1.3.0](https://github.com/esimov/triangle/releases/tag/v1.3.0) release, which as I mentioned now has a completely rewritten API, new logic for a better visual output, extended CLI options for a more advanced customization etc. If you don't have any objections I will close this issue.

**Comment by evilfunnybird** [comment]
So, indeed, the new version resolved this issue, thank you

**Comment by evilfunnybird** [comment]
One more bonus to 1.3.0 - svg files are more compact now (for me it's like 20-30%)
