### ISSUE TITLE
"Help" sometimes skip descriptions

### ISSUE THREAD

**Issue by evilfunnybird** [esimov/triangle#25]
In 1.3.0 --help option randomly skips descriptions
Screenshots made in Windows Terminal app (from Microsoft Store) with Windows Powershell command line
![image](https://user-images.githubusercontent.com/40058026/164060975-40489a41-3775-431a-bc0a-b65835915113.png)
![image](https://user-images.githubusercontent.com/40058026/164061192-38eabb92-c544-4723-a82d-af16b31b33e6.png)
![image](https://user-images.githubusercontent.com/40058026/164061293-4a4a9711-d128-44b8-a263-4e70d08b5cef.png)

**Comment by esimov** [comment]
I assume this is most likely a terminal related issue rather than something related to the library, but unfortunately I cannot test it, since I don't own a windows based machine.

**Comment by esimov** [comment]
Is this issue still happening? Did you tried it on other terminal? We can fill up an issue on the Go project Github page.

**Comment by evilfunnybird** [comment]
Issue is not occuring again
