### ISSUE TITLE
can't load package: package

### ISSUE THREAD

**Issue by roboto-cloud** [esimov/triangle#3]
issue installation:

**go install**
`can't load package: package .: no Go files in /home/roboto`

**go install triangle**
```
can't load package: package triangle: cannot find package "triangle" in any of:
        /usr/lib/go/src/triangle (from $GOROOT)
        /home/roboto/go/src/triangle (from $GOPATH)
```

**go env**
```
GOARCH="amd64"
GOBIN="/home/roboto/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/roboto/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build567200773=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

**Comment by esimov** [comment]
Based on provided information i think your environment variables are not initialized, in other terms the `.profile`, `.bashrc` or other init file is not sourced. Can you tell me where have you included the PATH variables? Did you set them manually or on the fly when your operating system is loaded?

**Comment by roboto-cloud** [comment]
Hi, I use .zshrc and oh my zsh with this plugins=(git git-extras zsh-completions zshmarks nvm virtualenv golang)
how do it using .zshrc ??

Regards,
....

**Comment by esimov** [comment]
Sorry, but this has nothing to do with the project itself, this is related to your environment settings so you should address them before to use the app. Google it and definitely you will find the answer. If GOPATH is set correctly this should work without problems. Taking this into consideration i will close the issue.
