### ISSUE TITLE
-in > Input file = all the *.jpg inside a folder

### ISSUE THREAD

**Issue by roboto-cloud** [esimov/triangle#4]
Someone know how work convert all the .jpg into a folder?

Regards,

**Comment by esimov** [comment]
This functionality is not supported, but it can be implemented.

**Comment by roboto-cloud** [comment]
I have a folder with 20.000 .jpg files and think this feature is essential for my case :)
Regards

**Comment by esimov** [comment]
@roboto-cloud implemented the requested feature. Test it and let me know how it's working. If you like the project please support it with a star.
