### ISSUE TITLE
svg output

### ISSUE THREAD

**Issue by imikod** [esimov/triangle#8]
would it be easy to implement? maybe with this https://github.com/ajstarks/svgo

**Comment by esimov** [comment]
It's possible, but the code needs a little bit of refactoring. With the Go interfaces it should be done relatively easily. I will take into consideration.

**Comment by esimov** [comment]
@imikod a little bit late but your wish is satisfied. Now you can export even to an `*.svg` file.

**Comment by imikod** [comment]
Thank you! Not late at all
