### ISSUE TITLE
Cannot find go install

### ISSUE THREAD

**Issue by enzyme69** [esimov/triangle#9]
I am a total noob with go, and so I followed your direction to install triangle, but there is no "go install" anywhere...

My directory:
<img width="1336" alt="screen shot 2018-02-05 at 9 05 38 pm" src="https://user-images.githubusercontent.com/3952687/35798939-559bd118-0ab8-11e8-95d7-4e56f89fa9de.png">

**Comment by enzyme69** [comment]
Ok never mind, somewhat the resulting "triangle app" goes into bin... and I need to use ./triangle -- weird.

**Comment by esimov** [comment]
Yes, that's the way how it's working.
